name: CD Example Production

on:
  push:
    branches:
      - main

jobs:
    deploy:
        name: CD Example Production
        runs-on: ubuntu-latest
        steps:
        - name: Checkout My Code
          uses: actions/checkout@v4  
        - name: SSH Connect
          uses: appleboy/ssh-action@v1 
          with:
            host: ${{ secrets.SERVER_HOST }}
            username: ${{ secrets.SERVER_USER }}
            password: ${{ secrets.SERVER_PASSWORD }}
            port: 22
            script: |
              echo "Berhasil Konek ke Server"
              if [ -d "/home/mda" ]; then
                echo "Ada folder MDA"
                cd /home/mda
                echo "Berhasil Masuk ke Folder MDA"
              else
                echo "Gak ada folder MDA, membuat folder..."
                mkdir /home/mda
                cd /home/mda
              fi

              if [ -d ".git"]; then
                echo "Ada folder .git, melakukan git pull"
                git remote set-url origin https://${ secrets.GIT_USERNAME }}:${{ secrets.GIT_PAT }}@github.com/dhimskyyy/cicd_database_example.git
                git pull origin main
              else
                echo "Gak ada folder .git, melakukan git clone"
                git clone https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_PAT }}@github.com/dhimskyyy/cicd_database_example.git
                cd cicd_database_example
              fi