name: CD Example Production

on:
  push:
    branches:
      - main
jobs:
    deploy:
        name: Deploy to Production
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: SSH Connect
          uses: appleboy/ssh-action@v1
          with:
            host: ${{ secrets.SERVER_HOST }}
            username: ${{ secrets.SERVER_USER }}
            password: ${{ secrets.SERVER_PASSWORD }}
            script: |
                  echo "Berhasil Konek ke Server"
                  if [ -d "/home/mda" ]; then
                    echo "Folder YIS sudah ada"
                    cd /home/mda
                    echo "Berhasil masuk ke folder MDA"
                  else
                    echo "Folder MDA belum ada, membuat folder..."
                    mkdir /home/mda
                    cd /home/mda