name: CICD Database Dev to Prod

on:
  push:
    branches:
      - main

jobs:
  db_cicd:
    name: Database CICD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Connect to Database
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            echo "Berhasil konek ke serverss"

            cd /home/mda
            echo "Berhasil pindah ke folder mda"

            docker-compose up -d #Menjalankan docker compose di server
            echo "Berhasil menjalankan docker compose di server