name: CICD Database Dev to Prod

on:
  push:
    branches:
      - main

jobs:
  db_cicd:
    name: Database CICD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Set up Python
      #   uses: appleboy/ssh-action@v1
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}
      #     username: ${{ secrets.SERVER_USER }}
      #     password: ${{ secrets.SSH_PASSWORD }}
      #     script: |
      #       echo "Berhasil konek ke server"